name: Manually deploy azure function dispatch

on:
  workflow_dispatch:
    inputs:
        environment:
          description: 'Define env name'     
          required: false
          default: 'prod'

jobs:
  deploy:
    name: manual deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Az CLI
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Create env file
      run: | # cp sample.env.yml env.yml
        cat > env.yml << EOF
        ${{ secrets.ENV_AZURE }}
        EOF
    - name: Install NPM dependencies
      run: yarn install --frozen-lockfile && SLS_DEBUG=*
    - name: Generate prisma 
      run: yarn gen
    - name: Deploy zip to azure
      run: |
        export AZURE_SUBSCRIPTION_ID=${{secrets.AZURE_SUBSCRIPTION_ID}}
        export AZURE_TENANT_ID=${{secrets.AZURE_TENANT_ID}}
        export AZURE_CLIENT_ID=${{secrets.AZURE_CLIENT_ID}}
        export AZURE_CLIENT_SECRET=${{secrets.AZURE_CLIENT_SECRET}} 
        yarn run azure
