name: run integration testing

on:
  pull_request:
    branches: [main, dev]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234567890
          POSTGRES_DB: serverless_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    - name: Unit testing
      run: yarn test
    - name: Integration testing
      run: |
        export AWS_ACCESS_KEY_ID = ${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        export AZURE_CON_STRING = ${{secrets.AZURE_CON_STRING}} 
        yarn prisma db push
        yarn test:integration